## 1. Allgemeine Erläuterungen im Fach Englisch

Die Bildungsstandards für die Erste Fremdsprache (Englisch/Französisch) sind aufgrund eines Beschlusses der Kultusministerkonferenz seit dem Schuljahr 2004/2005 bzw. 2005/2006 verbindliche Zielvorgaben für die Lehrplanentwicklung und die Lehrerbildung. Sie differenzieren nach angestrebtem Schulabschluss (HSA/MSA) und werden vom IQB in konkrete Testaufgaben umgesetzt („operationalisiert“).

Entscheidend für das Konzept der Bildungsstandards ist damit erstens, dass diese auf eine (kumulativ zu erweiternde) Basis theoretischen Fachwissens aufbauen. Da der Fokus auf der Lösung von fachlichen Problemen liegt, v.a. dem tatsächlichen Handeln(-können) und dem reflexiv-kritischen Bewerten(-können), wird dies über einen langfristigen Kompetenzaufbau angestrebt.

Entscheidend für das Konzept der Bildungsstandards ist zweitens, dass diese output-orientiert sind, also Zielformulierungen enthalten und lediglich Hinweise für die Lehrkräfte geben, wie diese erreicht werden können. Jede Schule bzw. Fachkonferenz soll in Form eines Schulcurriculums einen eigenen, den jeweiligen Schüler:innen angepassten, fördernden und differenzierenden Weg zu diesem Ziel finden.

Die den VERA-8-Arbeiten zugrundeliegenden Bildungsstandards beziehen sich auf die neunte bzw. die zehnte Klasse. Der relativ frühe Testzeitpunkt – vier Monate vor Ende der achten Klasse – ist mit Absicht gewählt, da auf diese Weise den Schüler:innen sowie den Lehrkräften genügend Zeit bleibt, dem Standort der Klasse im Hinblick auf den Haupt- bzw. Mittleren Schulabschluss Rechnung zu tragen und rechtzeitig Fördermaßnahmen einleiten zu können.

**Haftungsausschluss:**  
Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für Richtigkeit, Vollständigkeit und Aktualität der Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.
