project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/vera-info/
  title: "VERA-info"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/vera-info/
  search: false
  navbar:
    logo: IQB-klein.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
