project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/vera-info/
  title: "VERA"
  favicon: assets/favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/vera-info/
  repo-actions: []
  navbar:
    search: true
    logo: assets/iqb-logo-grey.png
  page-footer:
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - icon: assets/IQB-klein.png
        href: index.qmd
  sidebar: 
    style: "docked"
    search: true
    lang: de
    collapse-level: 1
    contents:
      - intro/literature.qmd
      - href: faq.qmd
        text: FAQ
      - href: info_laender.qmd
        text: Infos der Länder

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    css: assets/styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
