project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/vera-info/
  title: "VERA-info"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/vera-info/
  repo-actions: [issue]
  navbar:
    search: true
    logo: IQB-klein.png
  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - icon: IQB-klein.png
        href: index.qmd
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - href: index.qmd
        text: Start
      - section: "Einführung"
        contents:
          - href: intro/what_is.qmd
            text: Was ist VERA?
          - href: intro/booklets.qmd
            text: Bildungsstandards
          - href: intro/unit_structure.qmd
            text: Aufbau der Testaufgaben
          - href: intro/feedback.qmd
            text: Rückmeldung
      - section: "VERA3 Deutsch"
        contents:
          - href: v3_de/intro.qmd
            text: Überblick
          - section: "Lesen"
            contents:
              - href: v3_de/lesen/allgemein.qmd
                text: Teilkompetenz Lesen
              - href: v3_de/lesen/anregungen.qmd
                text: Anregungen für den Unterricht
              - href: v3_de/lesen/material.qmd
                text: Material
          - section: "Sprache"
            contents:
              - href: v3_de/sprache/allgemein.qmd
                text: Teilkompetenz Sprache
              - href: v3_de/sprache/bista-bezug.qmd
                text: Bezug zu Bildungsstandards
          - href: v3_de/literature.qmd
            text: Literatur

      - section: "VERA3 Mathematik"
        contents:
          - href: v3_ma/intro.qmd
            text: Überblick
          - href: v3_ma/ksm.qmd
            text: Kompetenzstufen
      - section: "VERA8 Deutsch"
        contents:
          - href: v8_de/intro.qmd
            text: Überblick


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
