---
title: "VERA-8 Fremdsprache"
lang: de
bibliography: bibliography.bib
csl: ../assets/apa.csl
format:
  html:
    toc: false
    other-links:
      - href: https://www.kmk.org/fileadmin/Dateien/veroeffentlichungen_beschluesse/2004/2004_10_15-Bildungsstandards-ersteFS-Haupt.pdf
        text: Bildungsstandards 1. Fremdsprache HSA
      - href: https://www.kmk.org/fileadmin/Dateien/veroeffentlichungen_beschluesse/2003/2003_12_04-BS-erste-Fremdsprache.pdf
        text: Bildungsstandards 1. Fremdsprache MSA 2003
---

Die Bildungsstandards für die Erste Fremdsprache (Englisch/Französisch) sind aufgrund eines Beschlusses der Kultusministerkonferenz [@KMKKultusministerkonferenz.2006] seit dem Schuljahr 2004/2005 bzw. 2005/2006 verbindliche Zielvorgaben für die Lehrplanentwicklung und die Lehrkräftebildung. Sie differenzieren nach angestrebtem Schulabschluss (HSA/MSA) und werden vom IQB in konkrete Testaufgaben umgesetzt („operationalisiert“).

Entscheidend für das Konzept der Bildungsstandards ist damit erstens, dass diese zwar auf eine (kumulativ zu erweiternde) Basis theoretischen Fachwissens aufbauen, aber -- aufgrund ihres Fokus auf der Lösung von fachlichen Problemen --  v. a. dem tatsächlichen Handeln(-können) und dem reflexiv-kritischen Bewerten(-können) den entscheidenden Stellenwert einräumen, angestrebt über einen langfristigen Kompetenzaufbau.

Entscheidend für das Konzept der Bildungsstandards ist zweitens, dass diese output-orientiert sind, also Zielformulierungen enthalten und lediglich Hinweise für die Lehrkräfte geben, wie diese erreicht werden können. Jede Schule bzw. Fachkonferenz soll in Form eines Schulcurriculums einen eigenen, den jeweiligen Schülerinnen und Schülern angepassten, fördernden und differenzierenden Weg zu diesem Ziel finden.

Die den VERA-8-Arbeiten zugrundeliegenden Bildungsstandards beziehen sich auf die neunte bzw. die zehnte Klasse. Der relativ frühe Testzeitpunkt – circa vier Monate vor Ende der achten Klasse –  ist mit Absicht gewählt, da auf diese Weise den Schülerinnen und Schülern sowie den Lehrkräften genügend Zeit bleibt, dem Standort der Klasse im Hinblick auf den Haupt- bzw. Mittleren Schulabschluss Rechnung tragen und rechtzeitig Fördermaßnahmen einleiten zu können.

Lesen Sie weiter:

* [Kompetenzmodell](standards.qmd): Gemeinsamer Europäischer Referenzrahmen, Kompetenzmodell entspr. Bildungsstandards.
* [Hörverstehen](listening.qmd): Ausführliche Erläuterungen zum Kompetenzbereich Hörverstehen. Je drei Beispielaufgaben für Englisch und Französisch.
* [Leseverstehen](reading.qmd): Ausführliche Erläuterungen zum Kompetenzbereich Leseverstehen. Je drei Beispielaufgaben für Englisch und Französisch.
* [Material für den Unterricht](material/index.qmd): Lernaufgaben und Übungen sprachübergreifend.
* [Literatur](literature.qmd): Hinweise auf weiterführende Beiträge und Monographien.

::: {.callout-note}
## Weiterentwicklung der Bildungsstandards

2023 wurden die Bildungsstandards für die erste Fremdsprache für den Ersten und Mittleren Schulabschluss [weiterentwickelt](https://www.iqb.hu-berlin.de/bista/WeiterentwicklungBiSta/) und von der KMK verabschiedet. Die vorliegenden Testaufgaben beziehen sich auf die Bildungsstandards, die 2004 und 2003 von der KMK beschlossen worden sind, da sich die Normierungsaufgaben für die neuen Bildungsstandards noch in der Entwicklung befinden.
:::

# Autor*innen

An den Texten dieses Kapitels haben im Auftrag des IQB folgende Personen mitgewirkt:

* **Englisch**: Lisa Marie Dillmann, Viktoria Anna Krämer, Prof. Dr. Henning Rossa, Daniel Mischa Helsper und Dr. Karoline Wirbatz
* **Französisch**: Prof. Dr. Hélène Martinez, Dr. Sophie Engelen und Maïa Roueire-Klitzke

Die abschließende Redaktion lag in den Händen des IQB.