---
title: "Ausgewählte Zusatzmaterealien"
lang: de
---

# Zeitschriften

Deutsch differenziert – Zeitschrift für die Grundschule (Westermann)

* Ausgabe 1/2022: Kinderlyrik – hören, lesen, gestalten, schreiben
* Ausgabe 1/2020: Sachtexte – Anschlusskommunikation anleiten und gestalten
* Ausgabe 4/2018: Leseanlässe – Wie Kinder Lesen als bedeutsam erfahren
* Ausgabe 3/2018: Comics – Lernen mit Bild und Text
* Ausgabe 2/2016: Lesespiele – Lesekompetenz spielerisch fördern
* Ausgabe 4/2016: Abenteuerliteratur – Fantasiewelten entdecken, Medien produktiv nutzen

Grundschule Deutsch (Friedrich Verlag)

* Ausgabe 76/2022: Reime, Gedichte, Sprachspiele
* Ausgabe 73/2022: Sachbücher
* Ausgabe 65/2020: Deutschunterricht digital
* Ausgabe 55/2017: Vorlesen
* Ausgabe 53/2017: In Geschichten eintauchen
* Ausgabe 50/2016: Fabeln
* Ausgabe 48/2015: Literarisches Lernen
* Ausgabe 30/2011: Verschiedene Kinder – verschiedene Bücher

Praxis Grundschule (Westermann)

* Ausgabe 5/2017: Von Bilderbuch bis Schmöker – Neue Kinderliteratur im Unterricht
* Ausgabe 6/2016: Lyrik in vielen Formen – Klang, Struktur und Sprache erkunden 

Praxis Deutsch – Zeitschrift für den Deutschunterricht (Friedrich Verlag)

* Ausgabe 272/2018: Literatur inklusiv
* Ausgabe 241/2013: Literarische Texte werten
* Ausgabe 231/2012: Lesekultur 

# Webseiten

[KMK-Bildungsstandards ausführlich](https://www.kmk.org/fileadmin/Dateien/veroeffentlichungen_beschluesse/2004/2004_10_15-Bildungsstandards-Deutsch-Primar.pdf)

[KMK-Bildungsstandards für den Unterricht erklärt](https://edoc.hu-berlin.de/bitstream/handle/18452/3773/1.pdf?sequence=1) 

[Lern- und Testaufgaben unterscheiden](http://www.kmk-format.de/Deutsch.html) 

[Lesekompetenz nach Rosebrock (2012) ausführlich erklärt](https://www.leseforum.ch/myUploadData/files/2012_3_Rosebrock.pdf) 

[Beispiele Methoden zur Förderung der Lesemotivation](https://www.lesen.bayern.de/buecher-fuer-kinder-jugendliche-und-junge-erwachsene/lesemotivation/) 

[Kompetenzstufenmodel zu den Bildungsstandards](https://www.iqb.hu-berlin.de/bista/ksm)

[Hinweise zur durchgängigen Leseförderung](https://biss-sprachbildung.de/pdf/biss-handreichung-durchgaengige-lesefoerderung.pdf) 

[Übersicht weiterer Diagnosemöglichkeiten](https://biss-sprachbildung.de/ueber-biss/biss-module/primarstufe-modul-p3-diagnose-und-foerderung-der-lesefluessigkeit-und-ihrer-voraussetzungen/) 

[Skala zur Einschätzung der Intonationsfähigkeit – ein Hilfsmittel zur weiteren Diagnose](https://biss-sprachbildung.de/btools/skala-zur-einschaetzung-der-intonationsfaehigkeit-des-phrasierten-lesens/) 

[Beispielübungen zur Segmentierung von Wörtern](https://bildungsserver.berlin-brandenburg.de/fileadmin/bbb/themen/sprachbildung/Lesecurriculum/Leseuebungen/Segmentierung.pdf)

[Eine Handreichung zum Schriftspracherwerb](https://cuvo.nibis.de/cuvo.php?p=download&upload=116)
 
[Über dialogisches Lesen](https://biss-sprachbildung.de/pdf/biss-broschuere-dialogisches-lesen-in-kitas.pdf) 

[Einfache Gespräche über Literatur als Beispiel in der vierten Jahrgangsstufe](https://www.friedrich-verlag.de/shop/kinderliteratur-werten-51630)

[Lautlese-Tandems für den Unterricht erklärt](https://biss-sprachbildung.de/pdf/biss-broschuere-lautlese-tandems.pdf) 

[Stiftung Lesen](https://www.stiftunglesen.de) 

[Lesestrategien in der Grundschule: Beispiel „Lesepiloten“](https://bildungsserver.berlin-brandenburg.de/lesepilot)

[Lesestrategietraining mit Sachtexten: Beispiellesetrainings „Filia“ und „Filius“](http://www.projektelis.eu/lehrmittel/)

[Beispielaufgaben zum Leseverstehen VERA 3](https://www.leseforum.ch/myUploadData/files/2015_1_Krelle.pdf)   

[Beispiele zur Binnendifferenzierung](https://www.schule-bw.de/faecher-und-schularten/sprachen-und-literatur/deutsch/unterrichtseinheiten/differenzierung) 

[Lesetraining: Beispiel „Lesen macht stark“](https://nzl.lernnetz.de/index.php/lesen-grundschule.html)

[Gängige Fördermethoden und Zusammenfassendes](https://www.biss-sprachbildung.de/pdf/biss-journal-3-november-2015-1.pdf)
