---
title: "Testauswertung und Ergebnisinterpretation"
lang: de
---

Die einfachste Form der Ergebnisrückmeldung besteht in der Angabe, wie viel Prozent der Schüler*innen eine Aufgabe korrekt gelöst haben (Lösungshäufigkeit). Wenn die Lehrkräfte hierzu Vergleichswerte erhalten (z. B. Ergebnisse anderer Klassen oder Schulen), ist ihnen eine näherungsweise Verortung ihrer Klasse möglich.

Zusammengefasste Klassenergebnisse eines VERA-Tests sind als zuverlässig zu betrachten und bieten für Lehrkräfte einen hohen Nutzen als Orientierungshilfe hinsichtlich der Kompetenzentwicklung ihrer Klasse/n im Vergleich zu anderen Klassen. Um diesen Nutzen, der den Ausgangspunkt für eine kompetenzorientierte Unterrichtsentwicklung bilden kann, nicht einzuschränken, sind spezielle Vorbereitungsmaßnahmen (teaching to the test) sowie unzulässige Hilfestellungen bei der Testdurchführung zu vermeiden.

Da die Schwierigkeitsgrade der meisten Aufgaben bekannt sind, kann durch eine statistische Berechnung für jede*n Schüler*in auch ein Wert für ihre/seine Kompetenz zurückgemeldet werden. Diese Werte (wie sie auch von PISA bekannt sind) werden durch Beschreibungen der Kompetenzniveaus inhaltlich veranschaulicht. Dieses individuelle Testergebnis bedarf jedoch ergänzender diagnostischer Informationen, z. B. zum individuellen Lernfortschritt, um für die/den einzelne*n Schüler*in diagnostisch aussagekräftig zu sein.
