---
title: "Aufbau der Testaufgaben"
lang: de
---

# Struktur

Die Testaufgaben bestehen aus einer Anleitung, einem Stimulus (z. B. Lese- oder Hörtext, Abbildung) und z. T. mehreren Aufgabenstellungen (den Items bzw. Teilaufgaben). Die Teilaufgaben sind in der Regel unabhängig voneinander lösbar. Die Lösung kann in Form einer Ankreuzaufgabe, als Lücken- bzw. Kurzantwort oder mit ausführlicher Darlegung des Lösungsweges gefordert werden.

# Erprobung

Die in den VERA-Testheften eingesetzten Aufgaben wurden von erfahrenen Lehrkräften aus allen Schulformen und allen Ländern entwickelt und erprobt, anschließend von Wissenschaftler*innen aus den jeweiligen Fachdidaktiken, die mit den Bildungsstandards vertraut sind, bewertet und überarbeitet. Fachvertreter*innen aus den Ländern begutachten und diskutieren die Aufgaben, die dann nach einer erneuten Überarbeitungsphase schließlich ein Jahr vor ihrem Einsatz an einer Stichprobe von ca. 3.000 Schüler*innen erprobt werden. 

Dieser aufwendige Vortest soll zum einen sicherstellen, dass die auf ihre fachdidaktische Güte überprüften Aufgaben sowohl fair (bspw. geschlechterneutral, Minderheiten nicht benachteiligend etc.) als auch trennscharf sind (d. h.: schwierigere Aufgaben werden eher von leistungsstärkeren als von leistungsschwächeren Schüler*innen gelöst). Zum anderen lassen sich über diesen Vortest realistische Schwierigkeitswerte der Aufgaben gewinnen, welche die Grundlage für die Zusammenstellung der Tests sind. 

# Punkte

Die Bepunktung des Tests ist für Lehrkräfte zum Teil etwas ungewöhnlich, da sie sich von der bekannten Bepunktung (z. B. in Klassenarbeiten) etwas unterscheidet. Damit das Testergebnis eindeutig interpretiert werden kann, dürfen nur vollständig gelöste Aufgaben als „richtig“ gewertet werden. Anders als bei Klassenarbeiten, bei denen die individuelle Leistungsfeststellung im Vordergrund steht, handelt es sich bei den Vergleichsarbeiten um diagnostische Tests, mit denen der Lernstand von Lerngruppen festgestellt werden soll. Zentral ist eine möglichst genaue Zuordnung des erzielten Lernstandes zu den in den Bildungsstandards beschriebenen fachlichen Anforderungen. Die Bewertung bzw. Anerkennung erbrachter Teilleistungen ist hierzu nicht erforderlich bzw. kann das Testergebnis nur anhand vollständig gelöster Aufgaben eindeutig interpretiert werden. 

# Keine Lernaufgaben

Es handelt sich also bei den in VERA verwendeten Aufgaben um Testaufgaben; sie sollen einzelne Aspekte der Bildungsstandards möglichst trennscharf und zuverlässig abprüfen. Für den Kompetenzerwerb eignen sich hingegen Lernaufgaben grundsätzlich besser. Die vorliegende Handreichung soll dazu beitragen, abgeleitet von den Testaufgaben Ideen für Unterrichtsaufgaben und Lernaufgaben zu entwickeln, die als bereicherndes Gestaltungselement kompetenzfördernd und lernwirksam im Unterricht einsetzbar sind.
