---
title: "Was sind VERA-Vergleichsarbeiten?"
lang: de
---

# Beschlüsse der Kultusministerkonferenz

Im Frühjahr jedes Jahres werden in den 3. und 8. Klassen der allgemeinbildenden Schulen in Deutschland parallel sogenannte Vergleichsarbeiten (oder kurz VERA) in den Fächern Mathematik, Deutsch und/oder erste Fremdsprache (Englisch/Französisch, nur VERA-8) und/oder im Fach Französisch in der zweiten Fremdsprache (nur VERA-8) geschrieben. VERA geht auf einen Beschluss der Kultusministerkonferenz zurück, schließt an ähnliche Erhebungen einzelner Länder in früheren Jahren an und wird jährlich durchgeführt. Die zentrale Funktion von VERA liegt in der Unterstützung der Lehrkräfte bei der Unterrichts- und Schulentwicklung. 

Die Länder haben sich im März 2012 auf gemeinsame Zielsetzungen und einheitliche Rahmenbedingungen sowie Regeln im Umgang mit den Daten und Ergebnissen verständigt. Mit der im März 2018 beschlossenen „Vereinbarung zur Weiterentwicklung der Vergleichsarbeiten (VERA)“ (vgl. Beschluss der Kultusministerkonferenz vom 08.03.2012 i. d. F. v. 15.03.2018) wurde die Funktion von VERA als Instrument der Schul- und Unterrichtsentwicklung noch einmal gestärkt. In diesem Rahmen wurden auch Verabredungen im Hinblick auf die Weiterentwicklung des Testinstruments getroffen, das seit dem VERA-Durchgang 2020 eingesetzt wird ([weiterlesen KMK](https://www.kmk.org/themen/qualitaetssicherung-in-schulen/bildungsmonitoring/verfahren-zur-qualitaetssicherung-auf-schulebene.html)).

# Aufgabenentwicklung

Das Institut zur Qualitätsentwicklung im Bildungswesen an der Humboldt-Universität zu Berlin (IQB) entwickelt im Auftrag der Länder die Testaufgaben und Ergänzungsmaterialien für VERA. 

# Durchführung

Zuständig für die Durchführung von VERA sind die Länder. Sie organisieren sowohl den Ablauf als auch die Ergebnisrückmeldung in eigener Verantwortung und haben dabei teilweise unterschiedliche Regelungen getroffen, da das Testverfahren in jeweils landesspezifische Strategien der Qualitätssicherung und Qualitätsentwicklung eingebettet ist und die konkreten Regelungen den Gegebenheiten vor Ort Rechnung tragen müssen. So werden zum einen die Arbeiten u. U. nicht in allen Fächern verpflichtend geschrieben; zum anderen unterscheidet sich die Form der Ergebnisrückmeldung. Auch die Bezeichnung für VERA variiert zwischen den Ländern – so sind z. B. auch Benennungen wie Kompetenztest, Lernstandserhebung oder KERMIT üblich. Die Testdurchführung und die Eingabe der Schüler*innenergebnisse liegt in der Regel in der Verantwortung der Lehrkräfte und in einigen Ländern bei externen Testleitungen.

Im Unterschied zu internationalen Schulleistungsuntersuchungen wie PISA, IGLU oder TIMSS ist VERA kein stichprobengestütztes Verfahren auf der Ebene des Schulsystems, mit dem die Leistungsfähigkeit des schulischen Bildungssystems beobachtet und evaluiert wird. VERA ist vielmehr ein Instrument der Unterrichtsentwicklung, mit dem Lehrkräfte feststellen können, inwieweit ihre Schüler*innen die abschlussbezogenen Bildungsstandards bereits ein Jahr vor ihrem Erreichen erfüllen. Die Ergebnisse liefern den Lehrkräften wichtige Hinweise auf Stärken und Schwächen in jeder einzelnen Klasse. Häufig unterrichten die Länder auch die Schüler*innen bzw. deren Eltern in zentraler, schriftlicher Form über die Ergebnisse. Die VERA-Ergebnisse bilden für die Lehrkräfte in Ergänzung zu ihren unterrichtspraktischen-professionellen Erfahrungen einen wichtigen Ansatzpunkt dafür, in welchen Bereichen im Unterricht verstärkt inhaltliche Schwerpunkte gesetzt werden müssen, damit möglichst alle Schüler*innen die Regelstandards erreichen. Wie dies erreicht werden kann und welche konkreten Maßnahmen dazu in der einzelnen Schule jeweils umgesetzt und anschließend auch überprüft werden müssen, sollte vor dem Hintergrund der Ergebnisse gemeinsam in den Kollegien und Fachkonferenzen diskutiert und vereinbart werden.
