---
title: "VERA Didaktische Handreichungen"
lang: de
---

Auf diesen Webseiten finden Sie ergänzende Texte zu den Lernstandserhebungen der Länder. Ziel der Texte ist es, das Verständnis für die Lernstandserhebungen zu fördern und die Nutzung der Ergebnisse zu verbessern. Zielgruppe sind vorrangig Lehrkräfte, die nach der Durchführung einer VERA-Testung die Auswertungsdaten besser verstehen und ihren Unterricht weiterentwickeln möchten. Die Struktur der Seiten folgt der Struktur der Bildungsstandards. Die Papierform dieser Texte ist als "Didaktische Handreichung Teile I+II" bekannt.

* [Einführung](intro/index.qmd)
* [VERA-3 Deutsch](v3_de/index.qmd)
* [VERA-3 Mathematik](v3_ma/index.qmd)

::: {.callout-important}
## Achtung: Webseite in Entwicklung

2026 beginnt die Veröffentlichung der Didaktischen Handreichungen Teile I und II mit den Fächern VERA-3 Deutsch und Mathematik in digitaler Form. Die Texte für VERA-8 sind in Vorbereitung.

:::

Es gibt neben den Texten an dieser Stelle weitere didaktische Handreichungen, die sich direkt auf die Testaufgaben eines Durchgangs beziehen (sog. "Didaktische Handreichung Teil III"). In diesen aufgabenbezogenen Handreichungen finden Sie konkrete Erläuterungen und Hilfestellungen sowie Vorschläge, wie diese Aufgaben für den Unterricht angepasst werden könnten. Diese Handreichungen sind nur einem begrenzten Personenkreis zugänglich, um die nötige Vertraulichkeit der Aufgaben zu gewährleisten. Daher ist dieser Teil nicht auf diesen Webseiten zu finden. Sie erhalten Einblick zu diesem Teil über Ihr Land bzw. die Einrichtung, die VERA für Sie durchführt.

# Redaktion

Die vorliegenden Texte werden unter Federführung des [IQB](https://www.iqb.hu-berlin.de/de/bista/implementation-und-ueberpruefung/vera/) veröffentlicht. Die jeweiligen Autor\*innen sind entweder im Kopf eines Dokumentes genannt oder zu Beginn eines größeren Seitenzweiges. Jeweils zu Beginn eines Jahres werden die Texte überarbeitet, um die Passung zum aktuellen VERA-Durchgang zu gewährleisten.
