---
title: "Kompetenzorientierung im Bereich Sprachgebrauch"
lang: de
bibliography: ../bibliography.bib
csl: ../../assets/apa.csl
---

In einem kompetenzorientierten Unterricht kommt es nicht in erster Linie darauf an, dass eine Reihe von Inhalten bzw. Themen abgearbeitet wird. Vielmehr wird vor allem darauf geachtet, was die Schüler\*innen am Ende von Unterrichtsphasen „können“. Dabei umfasst das Können mehr als das Wissen. Es hat vor allem auch eine motivationale Komponente. Zwar gibt es keine garantiert wirksamen Rezepte dafür, wie man Kinder langfristig dazu motivieren kann, dass sie sich gern mit Sprache und Sprachgebrauch beschäftigen. Wenn sie aber immer wieder die Erfahrung machen, dass sie die Aufgaben in diesem Bereich meistern können, trauen sie sich mehr zu, entwickeln mehr Lernfreude und sind bereit, sich anzustrengen.
Das Spektrum der Ziele im Bereich „Sprache und Sprachgebrauch untersuchen“ wird in den Standards wie folgt umrissen [@KMK2005, S. 9]:

> „Anknüpfend an ihre Spracherfahrungen entwickeln die Kinder ihr Sprachgefühl weiter und gehen bewusster mit Sprache um. In altersgemäßen, lebensnahen Sprach- und Kommunikationssituationen erfahren und untersuchen die Kinder die Sprache in ihren Verwendungszusammenhängen und gehen dabei auf die inhaltliche Dimension und die Leistung von Wörtern, Sätzen und Texten ein. Sie sprechen auch über Erfahrungen mit anderen Sprachen. Sie verfügen über ein Grundwissen an grammatischen Strukturen, einen Grundbestand an Begriffen und Verfahren zum Untersuchen von Sprache.“

Eine große, wenn nicht die größte Herausforderung im Unterricht besteht darin, dass die Spracherfahrungen der Kinder in der Regel sehr heterogen sind. Deshalb sind Individualisierung und Binnendifferenzierung nötig. Ein solcher Unterricht ist allerdings oft schwer zu organisieren. Die Standards sehen vor, dass dieser integrativ angelegt sein soll. Das heißt zum Beispiel, dass grundlegende wortart- und satzbezogene Begriffe zwar isolierend erarbeitet und geübt werden. Sie sollen dann aber im Rahmen anderer Kompetenzbereiche, vor allem in den Bereichen Lesen und Schreiben, immer wieder angewandt werden.

Die Kinder sollen allmählich lernen, Distanz zu dem zu gewinnen, was sie schon mehr oder weniger „können“. Sprache und Sprachgebrauch werden zum Gegenstand der Reflexion, die Sprachmittel werden aus den kommunikativen Situationen herausgelöst, dekontextualisiert. Gerade jüngeren Kindern fällt es oft schwer, sich beim Lesen oder Schreiben vom Inhalt zu lösen und ihre Aufmerksamkeit auf die sprachliche Ebene zu lenken. Deshalb ist es wichtig, dass dieser Fokuswechsel nicht zu schnell vollzogen wird. Es sollte zunächst immer darum gehen, Gesprochenes und Geschriebenes inhaltlich zu verstehen. Wenn an sprachlichem Material gearbeitet und entdeckend gelernt wird, kann der oft beschworenen Gefahr vorgebeugt werden, dass grammatische Termini nur Worthülsen sind und dass Begriffe und ihre Relationen nicht verstanden werden. In diesem Sinne lässt sich auch die Grobgliederung des Kompetenzbereichs „Sprache und Sprachgebrauch untersuchen“ in den Standards verstehen. Hier sind nämlich an erster Stelle Standards unter der Überschrift „sprachliche Verständigung untersuchen“ genannt, wobei es u. a. um „Verstehens- und Verständigungsprobleme“ geht. Es folgen Standards unter den Etiketten „an Wörtern, Sätzen, Texten arbeiten“, „Gemeinsamkeiten und Unterschiede von Sprachen entdecken“ und schließlich „grundlegende sprachliche Strukturen und Begriffe kennen und verwenden“ [@KMK2005, S. 13]. 
