---
title: "Schwerpunktthema: *Hilfsmittelfreie Aufgaben*"
lang: de
---

Die inhaltsbezogenen mathematischen Kompetenzen, die der Leitidee *Zahl* zuzuordnen sind, können nicht nur unter Rückgriff auf Hilfsmittel (wie etwa einen Taschenrechner) aufgebaut werden, sondern insbesondere auch bei Aktivitäten ohne Nutzung von Hilfsmitteln. Dieser Fokus ermöglicht die Überprüfung insbesondere folgender inhaltsbezogener mathematischer Kompetenzen zur Leitidee *Zahl*: Schüler\*innen *nutzen Rechengesetze, auch zum vorteilhaften Rechnen und sie nutzen zur Kontrolle Überschlagsrechnungen und andere Kontrollverfahren* (KMK, 2004, S. 10). Das Prüfen dieser Kompetenzen ist bei der Möglichkeit der Nutzung eines Taschenrechners nur beschränkt möglich, da Ergebnisse mithilfe des Taschenrechners bestimmt werden können. Dabei wird nicht erwartet, dass Schüler\*innen besonders langwierige Rechnungen mit vielstelligen Zahlen händisch durchführen. Es wäre auch im sonstigen Unterrichtsalltag nicht gefordert, dass Schüler\*innen diese ohne Hilfsmittel lösen. Die Entlastung von aufwendigen Rechnungen stellt gerade ein Potenzial von Taschenrechnern dar, weil die Nutzung eines Taschenrechners in diesem Fall andere wichtige didaktische Schwerpunkte wie das mathematische Problemlösen, Modellieren und Argumentieren unterstützt. Außerdem trägt die Nutzung des Taschenrechners an einer solchen Stelle zur Ausbildung der Kompetenz K5 (*Mit symbolischen, formalen und technischen Elementen der Mathematik umgehen*) bei, da Schüler\*innen in der Lage sein sollten, mathematische Werkzeuge wie den Taschenrechner sinnvoll und verständig einzusetzen (KMK, 2004, S. 9). Im hilfsmittelfreien Teil zur Leitidee *Zahl* geht es daher nicht um solche Aufgaben, bei denen der Taschenrechner eine Entlastung von aufwendigen Rechnungen bietet, sondern vor allem um die Überprüfung von Basisfähigkeiten hinsichtlich des Rechnens. Dies lässt sich nicht nur auf Grundlage der Bildungsstandards legitimieren. Dass Kompetenzen zum „Rechnen können“ notwendig sind, wird auch von Schüler\*innen wahrgenommen: Laut einer Studie der Stiftung Rechnen glauben 89 % der befragten Schüler\*innen, dass „Rechnen können“ wichtig für ihre Zukunft ist (Stiftung Rechnen, 2009).

Darüber hinaus kann der hilfsmittelfreie Teil zur Leitidee *Zahl* Aufgaben enthalten, bei denen ein Taschenrechner nicht zur Lösung genutzt werden kann, selbst wenn dieser zur Verfügung stünde, beispielsweise, wenn Schüler\*innen vorgegebene Anteile in einer Grafik einfärben sollen oder sie die Notwendigkeit der Zahlbereichserweiterung begründen sollen.

# Beispielaufgaben aus dem VERA-8 Kontext

Im folgenden Abschnitt wird anhand von vier hilfsmittelfreien Aufgaben dargestellt, welche *Allgemeinen mathematischen Kompetenzen* der Bildungsstandards mit den jeweiligen Aufgaben erhoben werden und wie diese Aufgaben vertiefend im Unterricht genutzt werden können. Dabei erfolgt die Aufgabenauswahl auf Basis der im vorherigen Abschnitt genannten inhaltsbezogenen mathematischen Kompetenzen zur Leitidee *Zahl*, die mit Hilfsmitteln nur eingeschränkt geprüft werden können. Die erste Aufgabe „Vorteilhaft Rechnen“ (siehe Beispielaufgabe 1) fokussiert die *Nutzung von Rechengesetzen zum vorteilhaften Rechnen*. Die zweite und dritte Aufgabe „Überschlagsrechnung“ bzw. „Überschlag doch mal“ prüfen jeweils die *Nutzung von Überschlagsrechnungen und anderen Verfahren* (siehe Beispielaufgaben 2 und 3). Außerdem wird mit der Aufgabe „Zwei Thermometeranzeigen“ (siehe Beispielaufgabe 4) exemplarisch der Aufgabentyp verdeutlicht, bei der ein Taschenrechner ohnehin nicht zur Lösung der Aufgabe genutzt werden kann.

Im Folgenden ist die Aufgabe „Vorteilhaft rechnen“ dargestellt.

> Grafik fehlt

Die Aufgabe „Vorteilhaft Rechnen“ prüft die Kompetenz *Mit symbolischen, formalen und technischen Elementen der Mathematik umgehen* (K5), indem die Lernenden gefordert sind, Assoziativ-, Kommutativ- und Distributivgesetz zu nutzen. Essentiell hierfür ist insbesondere ein tragfähiges Konzept der Multiplikation.

Eine gemeinsame Betrachtung der Aufgabe im Unterricht kann dazu genutzt werden, den Schüler\*innen den Vorteil der Nutzung von Rechengesetzen aufzuzeigen. So kann mit Teilaufgabe 1 die Nützlichkeit des Kommutativgesetzes aufgezeigt werden, indem das Produkt von 4 und 25 gebildet wird. Die Multiplikation einer Zahl mit 100 und das damit einhergehende „Anhängen von zwei Nullen“ bzw. die Verschiebung des Kommas um zwei Stellen nach rechts ist eine effektivere Maßnahme, als zunächst das Produkt von 4 und 0,1 zu bilden, um anschließend mit 25 zu multiplizieren.

Teilaufgabe 2 verdeutlicht die Nützlichkeit des Assoziativgesetzes. Werden zuerst der vierte und fünfte Faktor multipliziert und dies fortgeführt, entfallen aufwendige Kopfrechnungen, da dann der Spezialfall einer Multiplikation mit Null eintritt.

Für das Aufzeigen der Rechenvorteile, die das Distributivgesetz bietet, eignet sich Teilaufgabe 3 in besonderem Maße. Eine Umformung des Terms bringt eine Multiplikation mit dem Faktor 12 hervor, welche bedeutend einfacher ist, als zunächst die einzelnen Produkte auszurechnen und dann zu addieren.

Neben der Überprüfung, ob Schüler\*innen die Rechengesetze beherrschen, unterstreicht diese Aufgabe die Relevanz auch hilfsmittelfrei mit Zahlen operieren zu können. Ein Eintippen in den Taschenrechner oder das Nutzen eines anderen (digitalen) Hilfsmittels könnte hier sogar zu einem Mehraufwand führen.

Die nächsten beiden Aufgaben beziehen sich auf die inhaltsbezogene mathematische Kompetenz *(zur Kontrolle) Überschlagsrechnungen und andere Verfahren durchführen zu können*. Beispielaufgabe 2 zeigt die Aufgabe „Überschlagsrechnung“, in der bereits eine Rundung auf ganze Zehner zum Erfolg führt. Zur Lösung der Aufgabe ist die Kompetenz *Probleme mathematisch lösen* (K2) erforderlich, indem Schüler\*innen erkennen, dass hier das Abrunden der 91 auf 90 und das Aufrunden der 88 auf 90 einen adäquaten Überschlag darstellt (Antwortmöglichkeit 2).

> Grafik fehlt

Außerdem fordert die Aufgabe „Überschlagsrechnung“ die Kompetenz *Mit symbolischen, formalen und technischen Elementen der Mathematik umgehen* (K5) dadurch, dass Schüler\*innen Lösungs- und Kontrollverfahren ausführen. Wird Antwortmöglichkeit 4 ausgewählt, ist das ein Anzeichen dafür, dass die Idee des Überschlags nicht bekannt ist, weil mit den Zahlen nicht einfach im Kopf gerechnet werden kann. Es wird die Antwortmöglichkeit mit der scheinbar kleinsten Differenz zu 91∙88 ausgewählt. Die anderen Antwortmöglichkeiten sind nicht optimal, weil die gewählten Faktoren entweder zu klein sind (Antwortmöglichkeit 1), zweimal abgerundet (Antwortmöglichkeit 3) oder zweimal aufgerundet werden (Antwortmöglichkeit 5). Prinzipiell wäre diese Aufgabe auch für einen Prüfungsteil, der das Nutzen von Hilfsmitteln erlaubt, denkbar. Jedoch besteht die Gefahr, dass Schüler\*innen dann den Taschenrechner nutzen, um schnell das Ergebnis aller Antwortmöglichkeiten zu bestimmen, und dann den Vorschlag auswählen, der am nächsten an dem mit dem Taschenrechner bestimmten Ergebnis von 91∙88 liegt.

Eine gemeinsame Betrachtung der Aufgabe im Unterricht ist sinnvoll, weil sie Anlass zur Reflektion im Hinblick auf den Rechenaufwand und die Ergebnisgenauigkeit bietet. An dieser Stelle kann es sich lohnen, die Schüler\*innen die Lösungen der jeweiligen Antwortmöglichkeiten berechnen zu lassen und zu vergleichen. Dabei ist in der Aufgabe „Überschlagsrechnung“ ein direkter Überschlag erforderlich (direkte Angabe eines ungefähren Ergebnisses). Einen Kontrast dazu stellt der indirekte Überschlag dar, bei dem bestimmt wird, ob ein Überschlag über oder unter einem Ergebnis liegt (van den Heuvel-Panhuizen, 2008). Stellt sich beispielsweise die Frage, ob das Budget einer Galerie von 10 000 € reicht, um 91 Fotoleinwände zu kaufen, die je 88 € kosten, wäre 90∙90 € zwar immer noch der genauere Überschlag. Bei der Frage, ob der Überschlag unter einer vorgegebenen Zahl liegt, ist die Angabe von 100∙90 € an dieser Stelle jedoch auch denkbar, da das Aufrunden beider Zahlen hier eine sichere Antwort auf die Frage gibt, ob der Preis für die Fotoleinwände kleiner als der vorgegebene Wert von 10 000 € ist. Den Aufgabentypen liegen daher unterschiedliche Argumentationsprozesse zugrunde, die im Unterricht thematisiert werden können. Eine häufige Schwierigkeit besteht darin, dass die Überschlagsrechnung keinen genauen Regeln folgt, sondern gezielt Strategien ausgewählt werden müssen. Einen Gesprächsanlass dazu bieten die unterschiedlichen Strategien in der Tabelle 1. Mithilfe dieser Tabelle kann verdeutlicht werden, dass die Strategie des „Regelkonformen Rundens“ für das Galerie-Beispiel weniger geeignet ist, sondern eher auf die Strategien des „Geschickten Rundens“ oder der „Kompensation (Überschlag mit Ausgleichsrechnung)“ zurückgegriffen werden sollte. Schüler\*innen erfahren dabei, dass die Bewertung der Eignung einer Strategie immer situationsabhängig erfolgt.

> Grafik fehlt

Darüber hinaus können Aufgaben thematisiert werden, bei denen die Überschlagsrechnung nicht nur zum Vergleich mit genauen Ergebnissen oder als Vorabeinschätzung der zu erwartenden Größenordnung dient. Die Aufgabe „Überschlag doch mal“ (siehe Beispielaufgabe 3) bietet einen Anlass, zu thematisieren, dass eine ungefähre Abschätzung im Sachkontext ausreichend ist. Dabei stellt diese Aufgabe Anforderungen an die Kompetenz *Mathematisch modellieren* (K3), da die Realsituation („Wie viele Stunden werden in acht Schuljahren in der Schule verbracht?“) zunächst geeignet vereinfacht werden muss. Hierbei kommt sogenanntes Stützpunktwissen zum Tragen („Wie viele Wochen Schulferien gibt es?“, „Wie viele Tage pro Woche und wie viele Stunden am Tag verbringe ich in der Schule?“), mithilfe dessen geeignete Werte geschätzt werden. Diese Annahmen (z. B. 8 Schuljahre, 40 Schulwochen pro Jahr, 5 Schultage pro Schulwoche und 6 Stunden Schulzeit pro Tag) werden in ein mathematisches Modell überführt (8∙40∙5∙6). Durch mathematisches Arbeiten (evtl. auch unter Rückgriff auf Rechengesetze wie das Assoziativ- oder Kommutativgesetz), das Anforderungen an die Kompetenz *Mit symbolischen, formalen und technischen Elementen der Mathematik* (K5) stellt, erhalten Schüler\*innen hier das (exemplarische) Ergebnis 9600. Dieses muss anschließend im Sachzusammenhang interpretiert werden.

> Grafik fehlt

Für die Lösung der Aufgabe nutzen Schüler\*innen *sinntragende Vorstellungen von ganzen Zahlen entsprechend der Verwendungsnotwendigkeit* (KMK, 2004, S. 10). Dieses Beispiel der Temperatur bietet einen Anlass, den Schüler\*innen die Notwendigkeit der Zahlbereichserweiterung zu verdeutlichen, da den Schüler\*innen Temperaturen unter 0°C normalerweise bereits in ihrem Alltag begegnet sind und hierfür die aus der Grundschule bekannten natürlichen Zahlen nicht mehr ausreichen. Dabei muss das Rechnen mit natürlichen Zahlen überdacht werden, denn im Kontext von ganzen Zahlen verkleinert das Abziehen des Subtrahenden den Minuenden nicht zwangsläufig. Somit stellt diese Aufgabe Anforderungen an die Rechenfähigkeiten und -fertigkeiten der Schüler\*innen.

In dieser Aufgabe wird die Kompetenz *Mathematische Darstellungen verwenden* (K4) angesprochen, da der Abbildung der Thermometer wichtige Informationen entnommen werden müssen. Der sich anschließende Umgang mit den gegebenen Daten erfordert die Kompetenz *Mit symbolischen, formalen und technischen Elementen der Mathematik umgehen* (K5).

Letztendlich ist beim hilfsmittelfreien Arbeiten im Kontext der Leitidee *Zahl* das Ziel, dass Schüler\*innen einerseits Rechengesetze zum vorteilhaften Rechnen nutzen können. Andererseits ist ein genaues Rechnen nicht immer sinnvoll und erforderlich. Dabei ist eine wichtige Erfahrung für Schüler\*innen, dass sie nicht abhängig von ihrem Taschenrechner, sondern auch in der Lage sind, Überschlagsrechnungen abhängig vom Kontext durchzuführen.

Für weitere Anregungen für die Unterrichtspraxis sei auf die Kommentare zu den einzelnen Aufgaben in Teil III der didaktischen Handreichungen verwiesen.