---
title: "Literaturverzeichnis"
lang: de
---

Biehler, R. & Engel, J. (2015). Stochastik: Leitidee Daten und Zufall. In R. Bruder, L. Hefendehl-Hebeker, B. Schmidt-Thieme & H.-G. Weigand (Hrsg.), Handbuch der Mathematikdidaktik (S. 221–251). Berlin, Heidelberg: Springer.

Biehler, R. & Hartung, R. (2010). Leitidee Daten und Zufall. In W. Blum, C. Drüke-Noe, R. Hartung & O. Köller (Hrsg.), Bildungsstandards Mathematik: konkret. Sekundarstufe I: Aufgabenbeispiele, Unterrichtsanregungen, Fortbildungsideen (S. 51–80). Berlin: Cornelsen.

Blum, W. (2010). Einführung. In W. Blum, C. Drüke-Noe, R. Hartung, & O. Köller (Hrsg.), Bildungsstandards Mathematik: konkret. Sekundarstufe I: Aufgabenbeispiele, Unterrichtsanregungen, Fortbildungsideen (S. 14–32). Berlin: Cornelsen.

Eichler, A. & Vogel, M. (2013). Leitidee Daten und Zufall. Von konkreten Beispielen zur Didaktik der Stochastik. Wiesbaden: Springer Spektrum.

Greefrath, G. (2018). Anwendungen und Modellieren im Mathematikunterricht. Didaktische Perspektiven des Sachrechnens in der Sekundarstufe. Berlin: Springer Spektrum.

https://www.kmk.org/themen/qualitaetssicherung-in-schulen/bildungsstandards.html

Klieme, E., Avenarius, H., Blum, W., Döbrich, P., Gruber, H., Prenzel, M., Reiss, K., Riquarts, K., Rost, J., Tenorth, H.-E. & Vollmer, H. J. (2003). Zur Entwicklung nationaler Bildungsstandards. In BMBF (Hrsg.), Bildungsreform Band 1. Zur Entwicklung nationaler Bildungsstandards: Eine Expertise (S. 7–174). Berlin.

KMK (2004): Bildungsstandards im Fach Mathematik für den Mittleren Schulabschluss. Beschluss vom 4.12.2003. München: Luchterhand.

KMK (2005): Bildungsstandards im Fach Mathematik für den Hauptschulabschluss. Beschluss vom 15.10.2004. München, Neuwied: Luchterhand.

KMK (2005b). Bildungsstandards im Fach Mathematik für den Primarbereich. Beschluss vom 15.10.2004. München, Neuwied: Luchterhand.

KMK (2015). Bildungsstandards im Fach Mathematik für die Allgemeine Hochschulreife (Beschluss der Kultusministerkonferenz vom 18.10.2012). Köln: Carl Link.

Krüger, K., Sill, H.-D. & Sikora, C. (2015). Didaktik der Stochastik in der Sekundarstufe I. Berlin, Heidelberg: Springer Spektrum.

Leiss, D. & Blum, W. (2010). Beschreibung zentraler mathematischer Kompetenzen. In W. Blum, C. Drüke-Noe, R. Hartung & O. Köller (Hrsg.), Bildungsstandards Mathematik: konkret. Sekundarstufe I: Aufgabenbeispiele, Unterrichtsanregungen, Fortbildungsideen (S. 33–50). Berlin: Cornelsen.

OECD (2013). PISA 2012 Assessment and Analytical Framework: Mathematics, Reading, Science, Problem Solving and Financial Literacy. OECD Publishing.

Vogel, M. & Eichler A. (2010). Leitidee Daten und Zufall in der Sekundarstufe I. In A. Lindmeier & S. Ufer. (Hrsg.), Beiträge zum Mathematikunterricht 2010 (S. 879-882). Münster:  WTM-Verlag.

Wild, C.J., & Pfannkuch, M. (1999). Statistical Thinking in Empirical Enquiry. International Statistical Review 67(3), 223–248.

Winter, H. (1995). Mathematikunterricht und Allgemeinbildung. Mitteilungen der Gesellschaft für Didaktik der Mathematik 21(61), 37–46.