---
title: "VERA-8 Fremdsprache Material"
description: "Hörverstehen Textmapping"
lang: de
---

# Aufgabe

Die Schülerinnen und Schüler hören gemeinsam einen Text. Vor dem Hören wird je nach Text und dessen Funktion für eine bestimmte Lerngruppe vorgegeben, auf was sie sich konzentrieren sollen (z. B. die Kernaussage, die einzelnen Hauptaussagen, die zentralen Argumente, die aufgeführten Beispiele oder die ausgedrückten Emotionen). Während bzw. nach dem Hören notiert jeder, was er oder sie zum vorgegebenen Aspekt verstanden hat. Anschließend werden die Ergebnisse verglichen, d. h. alle Informationen werden stichpunktartig in einem Tafelbild gesammelt. 

In der Auswertung wird besprochen, welche Informationen von allen Lernenden und welche nur von einzelnen Lernenden verstanden worden sind. Dabei spielen vor allem erfolgreiche Vorgehensweisen, wie das Nutzen von Schlüsselwörtern, Wortfeldern, Stimmungen oder des Kontextes eine Rolle. Anschließend wird der Text ein zweites Mal gehört. Die Schülerinnen und Schüler ergänzen ggf. ihre Notizen, bevor sie abschließend erneut die Ergebnisse vergleichen. Auf der Grundlage ihrer Notizen können die Lernenden auch selbstständig Höraufgaben für Mitschülerinnen und Mitschüler bzw. andere Lerngruppen entwickeln.

# Vor dem Hören

Die Schülerinnen und Schüler überlegen ausgehend von einer Aufgabenstellung zum Hörverstehen, was sie über das in der Überschrift und Anweisung genannte Thema bereits wissen. Dazu erstellen sie in Gruppenarbeit eine Mindmap.

Zu den einzelnen Begriffen sammeln sie Synonyme, Ober- und Unterbegriffe, um den erforderlichen Wortschatz zu aktivieren. Gezielt nutzen sie dabei auch die Schlüsselbegriffe der Aufgabenstellung.

# Beim Hören

Die Lernenden nutzen die Begriffe ihrer Mindmap als Signalwörter. Sie markieren alle Begriffe, die sie heraushören. Erst danach beginnen sie, die Aufgabe zu bearbeiten. 

# Nach dem Hören

Die Lösungen werden verglichen und nach wiederholtem Hören ergänzt und ggf. verbessert. Danach wird besprochen, wie hilfreich das Vorgehen mit der Mindmap war und wie sie dieses Verfahren selbstständig bei der Bearbeitung anderer Höraufgaben nutzen können.
