---
title: "VERA-8 Fremdsprache Material"
description: "Hörverstehen Übungen"
lang: de
---

# Entwicklung des globalen Hörverstehens -- Filmbesprechung

Vorgehen: Fünf Schülerinnen und Schüler bereiten einen Kurzvortrag zu einem Film vor, den sie gesehen haben. Der Name des Filmes darf dabei nicht genannt werden. Es dürfen nur Filme ausgewählt werden, deren Name auch einen sinnvollen Bezug zum Inhalt des Filmes hat. Das sollte in der Stunde vorher besprochen werden.

Bevor die Vorträge stattfinden, werden von der Lehrkraft alle Titel und drei weitere auf Karten notiert. Diese werden dann an die Tafel geheftet. Während der Vorträge erschließen die Zuhörer, um welchen Film es sich handelt.

# Entwicklung des detaillierten Hörverstehens -- Maldiktat

## Variante 1

* Material: Postkarten, Fotos, Zeichnungen mit Darstellungen, die im thematischen Zusammenhang zu einer aktuellen Lernaufgabe stehen
* Vorgehen: Die Schülerinnen und Schüler sitzen Rücken an Rücken. Einer der Partner erhält ein Bild und beschreibt dieses möglichst genau. Der andere fertigt eine Skizze an, die am Ende der Aktivität mit der Vorlage verglichen wird.

## Variante 2

* Material: Hörbuchauszug, in dem ein Ort, ein Raum oder das Äußere einer Person sehr detailliert beschrieben wird
* Vorgehen: Die Schülerinnen und Schüler fertigen eine Skizze zum Text an. Die unterschiedlichen Darstellungen werden in einer Ausstellung gewürdigt. Zum Abschluss werden sie nochmals mit dem Hörtext abgeglichen.

# Entwicklung des selektiven Hörverstehens -- Selbst Aufgaben entwickeln

Die Lernenden hören eine Ankündigung oder ein Alltagsgespräch. Nach dem ersten Hören tauschen sie sich über die Situation aus, in der man üblicherweise einen solchen Text hört. Danach bestimmen sie die für den Hörer in dieser Situation wichtigen spezifischen Informationen (z. B. Daten, Preise, Orte).

Beim zweiten Hören achten sie gezielt auf diese Information(en). In Gruppen wird das Gehörte verglichen, die Schülerinnen und Schüler können selbst eine Höraufgabe entwerfen. Im Hinblick auf die Erweiterung und Festigung des Wortschatzes sollten darunter auch Mehrfachwahlaufgaben sein. Dabei lernen die Schülerinnen und Schüler durch das Formulieren unterschiedlicher Antwortmöglichkeiten gezielt Umschreibungen zu nutzen.